### ISSUE TITLE
I make dank memes and Russian stuff

### ISSUE THREAD

**Issue by deXxterlab97** [CSMarkBenchmark/CSMarkCore#1]
**Translations Info**

Информация перевода

Language: Russian (aka language of mother russia) 

Locale Code: RU/RUS (depending on context) but some domain name in russia is РФ 

**Translations**

Перевод

A list of **phrases or word(s)** in English to be translated into another language. 

Список фраз которые или слов на Английском которые нужно перевести на другом языке

Enter the translation after the arrow on a line with a **word or phrase** in English (so just copy paste what's already written cause it's english) 

Вводите перевод после стрелки на страку со словои или фразой на Английском 

### Example: 

Пример

Language: French

Язык: Французский 

Locale Code: fr

Локальный код: fr

- ``True`` -> Vrais

Прада -> Vrais

### Words or phrases that need translating:
Слова или фразы которые нужно перевести 

- ``single`` -> Одиночество (referring to relationship), не замужем (not married), один (one, as in number one), холостяк (bachelor). anyway if u are referring to let's say single core then u can use один but i need to know exact context
- ``multi`` -> мульти/много (context)
- ``json`` -> no. it's like translating a file extension to different language, u think if i make a document in russia it will have russian extension and render people from non russia unaccessible cause they can't read russian and might not have unicode package to display russians and russian = bad
- ``CSMarkCore`` -> really?
- ``App`` -> приложение
- ``Benchmark`` -> бенчмарк (literally benchmark written in russian, not common), тест (test, XD), тестирование (test, noun), тестировать (verb)
- ``Stress Test`` -> стресс-тест (same as above, literal translation) also stress test are written seperate
- ``We were unable to setup Error Reporting`` -> Мы не можем настроить отчеты об ошибках
- ``Don't turn off your PC`` -> не выключайте компьютер
- ``Warning: High Process Count Detected. This may affect your benchmarking scores.`` -> Внимание: высокое количество процессов. Это можно влиять на вашу результат тестирование
- ``By using CSMarkCore, you agree to our Privacy Policy located at`` -> Используя Х, вы соглашаетесь нашим политиком конфиденциальности, который находится в google.com
- ``By using CSMarkCore, you agree to our Terms of Service located at`` -> Используя Х, вы соглашаетесь нашим условием использования, который находится в google.com
- ``Detecting CLI Arguments...``(CLI meaning: Command Line Interface/Terminal) ->Обнаруживается аргументы Интерфейс командной строки (russian do not abbreviate this and use CLI if they do) / терминал (terminal)
- ``Starting Benchmarks...`` -> начинается тестирование
- ``Starting StressTests...`` -> начинается стресс-тест
- ``To exit this application, press ENTER.`` ->  Для выхода из этой приложении нажмите ENTER (no punctuation here except a period/full stop at the end, same goes to everything else, punctuation works just as in english minus the comma rules)

Note:
We appreciate your help translating CSMark and we'll try to implement these translations as soon as possible.

Замечание:
Мы благодарим вашу помощь за перквода CSMark и попытаемся добавлять при первой возможности

**Comment by deXxterlab97** [comment]
> > multi -> мульти/много (context)
> 
> Like Multi core or multi-threaded

много

**Comment by AluminiumTech** [comment]
You mentioned in the discord that the russian translations were in lower case.

Do you think it should be changed to be all caps?

**Comment by deXxterlab97** [comment]
yes, since english is upper case why would russian be different? + it's the beginning of the sentence i can rewrite them if u need

**Comment by AluminiumTech** [comment]
> yes, since english is upper case why would russian be different? + it's the beginning of the sentence i can rewrite them if u need

Okay

**Comment by AluminiumTech** [comment]
Oh and also, could you translate these?

``true`` -> 
``false`` -> 
``Locale`` ->
``CheckForUpdatesOnStartup`` ->
``ShowAvailableUpdates`` ->
``AutomaticallyDownloadAvailableUpdates`` ->
``AutomaticallyInstallUpdates`` ->
``CollectErrorInfoAndCrashStatistics`` ->

Thank You :)

**Comment by deXxterlab97** [comment]
all without breaks/spaces?

**Comment by AluminiumTech** [comment]
> all without breaks/spaces b/w words?

The ones I posted above just now? Yeah.

**Comment by deXxterlab97** [comment]
правдо
ложно
локаль
ПроверкаОбновленийПриЗапуске
ПоказатьДоступныеОбновлении
АвтоматичноСкачатьДоступныеОбновлении
АвтоматичноУстановлятьДоступныеОбновлении
СобиратьИнформацииОбОшибкеИСтатистикаСбоев

Спасибо :)

**Comment by AluminiumTech** [comment]
Thanks, I've implemented these translations and this should be included in 0.33.2
