### ISSUE TITLE
Russian Translations Update

### ISSUE THREAD

**Issue by AluminiumTech** [CSMarkBenchmark/CSMarkCore#9]
**Translations Info**

Language:

Locale Code:

**Translations**

A list of phrases or word(s) in English to be translated into another language. 

Enter the translation after the arrow on a line with a word or phrase in English

### Words or phrases that need translating:
- ``This application will automatically exit in 30 seconds...`` -> 

Note:
We appreciate your help translating CSMark and we'll try to implement these translations as soon as possible.

**Comment by deXxterlab97** [comment]
Программа автоматически закрывается через 30 секунд...

**Comment by AluminiumTech** [comment]
Thanks 👍

**Comment by AluminiumTech** [comment]
This has been added to CSMarkCore and will be part of CSMarkCore 0.33.3
